### ISSUE TITLE
Left column is too narrow / doesn't adapt to ideal width

### ISSUE THREAD

**Issue by ddossot** [nidi3/raml-doc#15]
As you can see, so much wrapping occurs that it's hard to make sense of the resources:

![screenshot from 2015-08-18 09 17 18](https://cloud.githubusercontent.com/assets/119028/9335753/b657ff7c-458a-11e5-87d8-da2b1894432a.png)

Having the column auto-adapt would be great.

**Comment by nidi3** [comment]
Resources are now displayed hierarchical. Is the column still too narow?

**Comment by ddossot** [comment]
I don't see much difference in term of width, but the hierarchical view with folding definitely helps. Long non-hierarchical resources are still pretty much crammed in the column:

![screenshot from 2015-08-19 09 14 50](https://cloud.githubusercontent.com/assets/119028/9361964/daf8e1f2-4652-11e5-9575-a7b0ce59410f.png)

**Comment by nidi3** [comment]
enough space now?

**Comment by ddossot** [comment]
Yes, it's beautiful!

![screenshot from 2015-08-20 09 00 07](https://cloud.githubusercontent.com/assets/119028/9388399/e666e562-4719-11e5-91d8-e341956b39a3.png)
