### ISSUE TITLE
Support collapsing of sub-resources

### ISSUE THREAD

**Issue by ddossot** [nidi3/raml-doc#16]
We have a small API ( https://api.unbounce.com/raml/v0.4/api.raml ) but the navigation bar on left is already pretty busy:

![screenshot from 2015-08-18 09 17 18](https://cloud.githubusercontent.com/assets/119028/9336295/9a3c05d8-458d-11e5-9e4b-ab83eebe7428.png)

It would be nice if the sub-resources could be collapsed/expanded, both manually and from the URL so we can share a link to the API doc in collapsed mode.

**Comment by nidi3** [comment]
The resource tree is expandable using the "expanded" query parameter in the URL

**Comment by ddossot** [comment]
It works great, thanks!

From my tests, I noticed that `?expanded=false` works but not `?expanded=true`, for the latter I have to use `?expanded` only. This is fine, I just want to make sure it behaves the way you wanted.

**Comment by nidi3** [comment]
Intended usage is: `?expanded` expands all, `?expanded=<list of resources>` expands just the defines resources

**Comment by ddossot** [comment]
Works great! Thanks!
