### ISSUE TITLE
Dynamically size/hide empty columns in request/response details

### ISSUE THREAD

**Issue by ddossot** [nidi3/raml-doc#18]
There's lot of empty space while useful data is crammed into small boxes / overflows out:

![screenshot from 2015-08-18 09 57 10](https://cloud.githubusercontent.com/assets/119028/9336674/a4f45e10-458f-11e5-95f6-d7223335c560.png)

BTW I really like the fact you use no pop-ups :+1:

**Comment by nidi3** [comment]
better now?

**Comment by ddossot** [comment]
Oh, yes, so much better, look at this:

![screenshot from 2015-08-20 09 01 34](https://cloud.githubusercontent.com/assets/119028/9388421/1abe1286-471a-11e5-82d4-5c35184d67d6.png)
