### ISSUE TITLE
Support use of resources with and without trailing slash when sending a request

### ISSUE THREAD

**Issue by sosap** [nidi3/raml-doc#47]
When using different resources such as

> /user:
>   ...
> /user/:
>   ...
> 

then raml-doc will consider different resources when creating the html docs. However, the same call is sent to the web service for both resources when using the "send request" button.

It would be great if raml-doc respects trailing slashes indicating different web service calls when using "send request".

**Comment by nidi3** [comment]
I see the issue, but what would be a use case for `/user` being different from `/user/` ?

**Comment by nidi3** [comment]
Made a quick test and I cannot reproduce the issue.
Which browser do you use?
What looks the RAML like?

**Comment by sosap** [comment]
sorry, sorry, my fault. The problem is not related to raml-doc but to the tool chain. The mock service in use eats trailing slashes.

The use case for using trailing slashes in our web services is that / retrieves a list of items. This can certainly be expressed differently, it's simply a choice of the developers and it's a valid naming convention for resources.
