### ISSUE TITLE
Allow deep linking to a particular resource method

### ISSUE THREAD

**Issue by ddossot** [nidi3/raml-doc#48]
It would be nice to be able to provide a link that drills down to a particular method, maybe by using an anchor and some JavaScriptey magic?

**Comment by nidi3** [comment]
You mean `?method=get`? It already exists.
But I just realised that an anchor would be better as it also scrolls to the correct location.

**Comment by ddossot** [comment]
Oh I didn't know `?method` was supported (or I did I forgot :sob: ). But yeah, the anchor takes care of positioning so thanks :+1:
